export const SEARCH_ALIASES: Record<string, string[]> = {
  ayuda: [
    'dswd',
    'aics',
    'assistance',
    'cash assistance',
    'financial aid',
    'benefits',
    'social pension',
    '4ps',
    'walang gutom',
    'emergency cash transfer',
    'livelihood',
  ],
  aid: [
    'ayuda',
    'assistance',
    'dswd',
    'aics',
    'benefits',
    'cash assistance',
    'financial aid',
  ],
  assistance: [
    'ayuda',
    'dswd',
    'aics',
    'cash assistance',
    'financial aid',
    'social pension',
  ],
  benefits: [
    'ayuda',
    'assistance',
    'dswd',
    '4ps',
    'social pension',
    'philhealth',
    'pagibig',
    'sss',
  ],
  dswd: [
    'ayuda',
    'aics',
    '4ps',
    'walang gutom',
    'social pension',
    'emergency cash transfer',
    'sustainable livelihood',
    'student cash for work',
  ],
  aics: [
    'dswd',
    'ayuda',
    'cash assistance',
    'medical assistance',
    'educational assistance',
    'burial assistance',
    'transportation assistance',
  ],
  pension: [
    'social pension',
    'senior citizen',
    'elderly',
    'older persons',
    'dswd',
  ],
  senior: [
    'social pension',
    'senior citizen',
    'elderly',
    'older persons',
    'dswd',
  ],
  gutom: [
    'walang gutom',
    'food credits',
    'food stamp',
    'dswd',
    'beneficiary',
  ],
  food: [
    'walang gutom',
    'food credits',
    'food stamp',
    'dswd',
  ],
  livelihood: [
    'sustainable livelihood',
    'slp',
    'negosyo',
    'capital',
    'employment',
    'dswd',
  ],
  negosyo: [
    'livelihood',
    'sustainable livelihood',
    'slp',
    'capital',
    'dswd',
  ],
  student: [
    'student aid',
    'cash-for-work',
    'cash for work',
    'tara basa',
    'educational assistance',
    'scholarship',
    'dswd',
  ],
  estudyante: [
    'student',
    'student aid',
    'cash-for-work',
    'educational assistance',
    'scholarship',
    'dswd',
  ],
  calamity: [
    'disaster',
    'emergency cash transfer',
    'ect',
    'evacuation',
    'relief',
    'dswd',
  ],
  disaster: [
    'calamity',
    'emergency cash transfer',
    'ect',
    'evacuation',
    'relief',
    'dswd',
  ],
  '4ps': [
    'pantawid',
    'pantawid pamilya',
    'conditional cash transfer',
    'household validation',
    'dswd',
  ],
  national: [
    'national id',
    'philsys',
    'philid',
    'ephilid',
    'digital national id',
    'trn',
    'valid id',
  ],
  philsys: [
    'national id',
    'philid',
    'ephilid',
    'digital national id',
    'trn',
    'transaction reference number',
  ],
  philid: [
    'national id',
    'philsys',
    'ephilid',
    'digital national id',
    'trn',
  ],
  ephilid: [
    'national id',
    'philsys',
    'philid',
    'digital national id',
    'valid id',
  ],
  trn: [
    'transaction reference number',
    'national id',
    'philsys',
    'philid',
    'registration slip',
  ],
  otp: [
    'phishing',
    'scam',
    'mpin',
    'password',
    'account takeover',
    'stolen phone',
    'sim',
  ],
  mpin: [
    'otp',
    'phishing',
    'scam',
    'password',
    'gcash',
    'maya',
  ],
  sim: [
    'otp',
    'stolen phone',
    'lost phone',
    'phone stolen',
    'account access',
  ],
  phone: [
    'stolen phone',
    'lost phone',
    'sim',
    'otp',
    'gcash',
    'maya',
  ],
  nanakaw: [
    'stolen',
    'stolen phone',
    'lost phone',
    'phone stolen',
    'wallet',
  ],
  trabaho: [
    'work',
    'job',
    'first job',
    'requirements',
    'resume',
    'interview',
    'sss',
    'payroll',
  ],
  work: [
    'trabaho',
    'job',
    'first job',
    'requirements',
    'resume',
    'interview',
    'payroll',
  ],
  job: [
    'trabaho',
    'work',
    'first job',
    'requirements',
    'resume',
    'interview',
    'payroll',
  ],
  resume: [
    'cv',
    'biodata',
    'no experience',
    'fresh graduate',
    'first job',
    'job application',
  ],
  cv: [
    'resume',
    'biodata',
    'job application',
    'first job',
  ],
  biodata: [
    'resume',
    'cv',
    'job application',
    'first job',
  ],
  interview: [
    'job interview',
    'first job',
    'answers',
    'hr',
    'expected salary',
  ],
  sweldo: [
    'salary',
    'payday',
    'budget',
    'payroll',
    'bank account',
  ],
  sahod: [
    'salary',
    'payday',
    'budget',
    'payroll',
    'bank account',
  ],
  salary: [
    'sweldo',
    'sahod',
    'payday',
    'budget',
    'payroll',
  ],
  payroll: [
    'salary',
    'sweldo',
    'bank account',
    'first job',
    'requirements',
  ],
  rent: [
    'renting',
    'apartment',
    'bedspace',
    'deposit',
    'moving out',
    'landlord',
  ],
  apartment: [
    'rent',
    'renting',
    'bedspace',
    'deposit',
    'utilities',
  ],
  bedspace: [
    'rent',
    'renting',
    'apartment',
    'utilities',
    'moving out',
  ],
  upa: [
    'rent',
    'renting',
    'apartment',
    'deposit',
  ],
  bumukod: [
    'moving out',
    'rent',
    'budget',
    'utilities',
    'adulting',
  ],
  utilities: [
    'utility bills',
    'electricity',
    'water',
    'internet',
    'kuryente',
    'tubig',
  ],
  kuryente: [
    'electricity',
    'utility bills',
    'meralco',
    'disconnection',
  ],
  tubig: [
    'water',
    'utility bills',
    'maynilad',
    'disconnection',
  ],
  meralco: [
    'electricity',
    'kuryente',
    'utility bills',
  ],
  maynilad: [
    'water',
    'tubig',
    'utility bills',
  ],
  loan: [
    'online lending',
    'loan app',
    'ola',
    'utang',
    'pautang',
    'debt',
    'harassment',
    'collection',
  ],
  utang: [
    'loan',
    'online lending',
    'loan app',
    'ola',
    'pautang',
    'debt',
  ],
  pautang: [
    'loan',
    'online lending',
    'loan app',
    'utang',
    'ola',
  ],
  ola: [
    'online lending',
    'loan app',
    'loan',
    'utang',
    'harassment',
  ],
  harassment: [
    'online lending',
    'loan app',
    'collection',
    'data privacy',
  ],
  recruiter: [
    'fake job',
    'job scam',
    'illegal recruitment',
    'placement fee',
    'ofw',
    'dmw',
  ],
  recruitment: [
    'fake job',
    'job scam',
    'illegal recruitment',
    'placement fee',
    'ofw',
    'dmw',
  ],
  ofw: [
    'fake job',
    'job scam',
    'illegal recruitment',
    'placement fee',
    'dmw',
    'poea',
  ],
  'job scam': [
    'fake job',
    'recruiter',
    'illegal recruitment',
    'placement fee',
    'training fee',
  ],
  'fake job': [
    'job scam',
    'recruiter',
    'illegal recruitment',
    'placement fee',
    'training fee',
  ],
  'placement fee': [
    'fake job',
    'job scam',
    'illegal recruitment',
    'recruiter',
    'ofw',
  ],
}
