export const SEARCH_ALIASES: Record<string, string[]> = {
  ayuda: [
    'dswd',
    'aics',
    'assistance',
    'cash assistance',
    'financial aid',
    'benefits',
    'social pension',
    '4ps',
    'walang gutom',
    'emergency cash transfer',
    'livelihood',
  ],
  aid: [
    'ayuda',
    'assistance',
    'dswd',
    'aics',
    'benefits',
    'cash assistance',
    'financial aid',
  ],
  assistance: [
    'ayuda',
    'dswd',
    'aics',
    'cash assistance',
    'financial aid',
    'social pension',
  ],
  benefits: [
    'ayuda',
    'assistance',
    'dswd',
    '4ps',
    'social pension',
    'philhealth',
    'pagibig',
    'sss',
  ],
  dswd: [
    'ayuda',
    'aics',
    '4ps',
    'walang gutom',
    'social pension',
    'emergency cash transfer',
    'sustainable livelihood',
    'student cash for work',
  ],
  aics: [
    'dswd',
    'ayuda',
    'cash assistance',
    'medical assistance',
    'educational assistance',
    'burial assistance',
    'transportation assistance',
  ],
  pension: [
    'social pension',
    'senior citizen',
    'elderly',
    'older persons',
    'dswd',
  ],
  'senior pension': [
    'social pension',
    'senior citizen',
    'elderly',
    'older persons',
    'dswd',
  ],
  senior: [
    'social pension',
    'senior citizen',
    'elderly',
    'older persons',
    'dswd',
  ],
  gutom: [
    'walang gutom',
    'food credits',
    'food stamp',
    'dswd',
    'beneficiary',
  ],
  'walang gutom': [
    'food credits',
    'food stamp',
    'ebt',
    'dswd',
    'beneficiary',
  ],
  food: [
    'walang gutom',
    'food credits',
    'food stamp',
    'dswd',
  ],
  'food stamp': [
    'walang gutom',
    'food credits',
    'ebt',
    'dswd',
  ],
  livelihood: [
    'sustainable livelihood',
    'slp',
    'negosyo',
    'capital',
    'employment',
    'dswd',
  ],
  negosyo: [
    'livelihood',
    'sustainable livelihood',
    'slp',
    'capital',
    'dswd',
  ],
  slp: [
    'sustainable livelihood',
    'livelihood',
    'negosyo',
    'capital',
    'dswd',
  ],
  student: [
    'student aid',
    'cash-for-work',
    'cash for work',
    'tara basa',
    'educational assistance',
    'scholarship',
    'dswd',
  ],
  'cash for work': [
    'cash-for-work',
    'student cash for work',
    'tara basa',
    'kalahi cidss',
    'dswd',
  ],
  'cash-for-work': [
    'cash for work',
    'student cash for work',
    'tara basa',
    'kalahi cidss',
    'dswd',
  ],
  'tara basa': [
    'student cash for work',
    'cash for work',
    'tutoring',
    'dswd',
  ],
  estudyante: [
    'student',
    'student aid',
    'cash-for-work',
    'educational assistance',
    'scholarship',
    'dswd',
  ],
  calamity: [
    'disaster',
    'emergency cash transfer',
    'ect',
    'evacuation',
    'relief',
    'dswd',
  ],
  bagyo: [
    'calamity',
    'disaster',
    'emergency cash transfer',
    'cash aid',
    'relief',
    'dswd',
  ],
  baha: [
    'calamity',
    'disaster',
    'emergency cash transfer',
    'cash aid',
    'relief',
    'dswd',
  ],
  'cash aid': [
    'ayuda',
    'cash assistance',
    'financial aid',
    'emergency cash transfer',
    'dswd',
  ],
  'bagyo cash aid': [
    'emergency cash transfer',
    'disaster cash aid',
    'calamity',
    'relief',
    'dswd',
  ],
  ect: [
    'emergency cash transfer',
    'disaster cash aid',
    'calamity',
    'relief',
    'dswd',
  ],
  disaster: [
    'calamity',
    'emergency cash transfer',
    'ect',
    'evacuation',
    'relief',
    'dswd',
  ],
  accident: [
    'road accident',
    'road crash',
    'car accident',
    'motorcycle accident',
    'police report',
    'insurance claim',
    '911',
  ],
  'road accident': [
    'accident',
    'road crash',
    'car accident',
    'motorcycle accident',
    'police report',
    'traffic accident',
    'insurance claim',
    '911',
  ],
  'road crash': [
    'road accident',
    'traffic accident',
    'police report',
    'mmda',
    '911',
  ],
  'car accident': [
    'road accident',
    'road crash',
    'traffic accident',
    'police report',
    'insurance claim',
  ],
  'motorcycle accident': [
    'road accident',
    'road crash',
    'traffic accident',
    'police report',
    'insurance claim',
  ],
  'traffic accident': [
    'road accident',
    'road crash',
    'police report',
    'mmda',
    '911',
  ],
  'police report': [
    'road accident',
    'road crash',
    'insurance claim',
    'incident report',
    'blotter',
  ],
  'insurance claim': [
    'road accident',
    'police report',
    'incident report',
    'photos',
    'documents',
  ],
  'medical emergency': [
    'hospital documents',
    'hospital emergency',
    'philhealth hospital',
    'emergency contact',
    'ambulance',
    '911',
    'hmo',
    'billing',
    'social service',
  ],
  'hospital documents': [
    'medical emergency',
    'philhealth hospital',
    'patient documents',
    'hmo',
    'billing',
    'social service',
  ],
  'hospital emergency': [
    'medical emergency',
    'hospital documents',
    'ambulance',
    '911',
    'emergency contact',
  ],
  'philhealth hospital': [
    'medical emergency',
    'hospital documents',
    'philhealth',
    'philhealth benefits',
    'philhealth mdr',
    'claim form 1',
    'billing',
    'social service',
  ],
  'philhealth benefits': [
    'philhealth hospital',
    'hospital bill',
    'case rate',
    'philhealth mdr',
    'claim form 1',
    'discharge billing',
  ],
  'hospital bill': [
    'philhealth benefits',
    'philhealth hospital',
    'hospital assistance',
    'malasakit center',
    'medical assistance',
    'billing',
    'social service',
    'hmo',
  ],
  'hospital assistance': [
    'hospital bill',
    'social service',
    'medical assistance',
    'malasakit center',
    'public hospital',
  ],
  'medical assistance': [
    'hospital assistance',
    'hospital bill',
    'social service',
    'malasakit center',
    'aics',
    'pcso',
    'maifip',
  ],
  malasakit: [
    'malasakit center',
    'hospital assistance',
    'medical assistance',
    'social service',
    'public hospital',
  ],
  'malasakit center': [
    'malasakit',
    'hospital assistance',
    'medical assistance',
    'social service',
    'public hospital',
  ],
  'public hospital': [
    'hospital assistance',
    'social service',
    'medical social worker',
    'malasakit center',
    'hospital bill',
  ],
  'case rate': [
    'philhealth benefits',
    'philhealth hospital',
    'hospital bill',
    'billing',
  ],
  'philhealth mdr': [
    'philhealth benefits',
    'philhealth hospital',
    'member data record',
    'hospital documents',
  ],
  'member data record': [
    'philhealth mdr',
    'philhealth benefits',
    'hospital documents',
  ],
  'claim form 1': [
    'philhealth benefits',
    'philhealth hospital',
    'philhealth mdr',
    'hospital bill',
  ],
  'discharge billing': [
    'philhealth benefits',
    'hospital bill',
    'billing',
    'social service',
  ],
  hmo: [
    'medical emergency',
    'hospital documents',
    'hospital bill',
    'philhealth benefits',
    'billing',
    'coverage',
  ],
  ambulance: [
    'medical emergency',
    'hospital emergency',
    '911',
    'emergency contact',
  ],
  ambulansya: [
    'ambulance',
    'medical emergency',
    'hospital emergency',
    '911',
  ],
  billing: [
    'medical emergency',
    'hospital documents',
    'philhealth',
    'philhealth benefits',
    'hospital bill',
    'hmo',
    'social service',
  ],
  'social service': [
    'medical emergency',
    'hospital documents',
    'philhealth',
    'philhealth benefits',
    'hospital bill',
    'hospital assistance',
    'malasakit center',
    'public hospital',
    'billing',
    'medical social worker',
  ],
  'medical social worker': [
    'social service',
    'hospital assistance',
    'malasakit center',
    'public hospital',
    'hospital bill',
  ],
  maifip: [
    'medical assistance',
    'hospital assistance',
    'malasakit center',
    'social service',
  ],
  maipp: [
    'medical assistance',
    'hospital assistance',
    'malasakit center',
    'social service',
  ],
  gamot: [
    'medicine',
    'generic medicine',
    'generic',
    'reseta',
    'pharmacy',
    'fda verification',
    'fake medicine',
  ],
  medicine: [
    'gamot',
    'generic medicine',
    'generic',
    'prescription',
    'pharmacy',
    'licensed pharmacy',
    'fda verification',
  ],
  generic: [
    'generic medicine',
    'gamot',
    'medicine',
    'active ingredient',
    'cheaper medicine',
  ],
  'generic medicine': [
    'generic',
    'gamot',
    'medicine',
    'active ingredient',
    'cheaper medicine',
    'licensed pharmacy',
  ],
  reseta: [
    'prescription',
    'gamot',
    'generic medicine',
    'pharmacy',
  ],
  prescription: [
    'reseta',
    'medicine',
    'generic medicine',
    'pharmacy',
  ],
  pharmacy: [
    'licensed pharmacy',
    'gamot',
    'medicine',
    'generic medicine',
    'fda verification',
  ],
  'licensed pharmacy': [
    'pharmacy',
    'fda verification',
    'medicine',
    'generic medicine',
    'fake medicine',
  ],
  'fda verification': [
    'fda portal',
    'fda registered',
    'medicine',
    'fake medicine',
    'counterfeit medicine',
    'licensed pharmacy',
  ],
  'fda portal': [
    'fda verification',
    'fda registered',
    'medicine',
    'fake medicine',
  ],
  'fda registered': [
    'fda verification',
    'fda portal',
    'medicine',
    'licensed pharmacy',
  ],
  'fake medicine': [
    'counterfeit medicine',
    'fda verification',
    'unregistered medicine',
    'licensed pharmacy',
    'gamot',
  ],
  'counterfeit medicine': [
    'fake medicine',
    'fda verification',
    'unregistered medicine',
    'licensed pharmacy',
  ],
  'unregistered medicine': [
    'fake medicine',
    'counterfeit medicine',
    'fda verification',
    'licensed pharmacy',
  ],
  'office message': [
    'ask office',
    'office help',
    'requirements',
    'customer support',
    'paper trail',
    'reference number',
  ],
  'ask office': [
    'office message',
    'office help',
    'requirements',
    'appointment',
    'office hours',
    'documents',
  ],
  'office help': [
    'ask office',
    'office message',
    'requirements',
    'customer support',
    'paper trail',
  ],
  'magtanong': [
    'ask office',
    'office message',
    'requirements',
    'documents',
    'pabalik balik',
  ],
  'pabalik balik': [
    'office message',
    'ask office',
    'requirements',
    'documents',
    'paper trail',
  ],
  requirements: [
    'documents',
    'ask office',
    'office message',
    'appointment',
    'fees',
    'office hours',
  ],
  documents: [
    'requirements',
    'ask office',
    'office message',
    'proof',
    'paper trail',
  ],
  'paper trail': [
    'reference number',
    'proof',
    'screenshot',
    'receipt',
    'office message',
  ],
  'reference number': [
    'paper trail',
    'ticket number',
    'follow up',
    'office message',
  ],
  'customer support': [
    'support message',
    'office message',
    'reference number',
    'follow up',
  ],
  'support message': [
    'customer support',
    'office message',
    'paper trail',
  ],
  'follow up': [
    'reference number',
    'paper trail',
    'office message',
    'customer support',
  ],
  '4ps': [
    'pantawid',
    'pantawid pamilya',
    'conditional cash transfer',
    'household validation',
    'dswd',
  ],
  national: [
    'national id',
    'philsys',
    'philid',
    'ephilid',
    'digital national id',
    'trn',
    'valid id',
  ],
  philsys: [
    'national id',
    'philid',
    'ephilid',
    'digital national id',
    'trn',
    'transaction reference number',
  ],
  philid: [
    'national id',
    'philsys',
    'ephilid',
    'digital national id',
    'trn',
  ],
  ephilid: [
    'national id',
    'philsys',
    'philid',
    'digital national id',
    'valid id',
  ],
  trn: [
    'transaction reference number',
    'national id',
    'philsys',
    'philid',
    'registration slip',
  ],
  otp: [
    'phishing',
    'scam',
    'mpin',
    'password',
    'account takeover',
    'stolen phone',
    'sim',
    'gcash otp',
  ],
  mpin: [
    'otp',
    'phishing',
    'scam',
    'password',
    'gcash',
    'maya',
  ],
  'gcash otp': [
    'gcash',
    'otp',
    'mpin',
    'account takeover',
    'device registration',
    'phishing',
  ],
  'gcash mpin': [
    'gcash',
    'mpin',
    'otp',
    'password',
    'fake support',
  ],
  'gcash support': [
    'gcash',
    'fake support',
    'help center',
    'gigi',
    'report scam',
  ],
  'fake support': [
    'gcash support',
    'report scam',
    'recovery fee',
    'phishing',
  ],
  'wrong send': [
    'gcash',
    'maling send',
    'wrong number',
    'send money',
    'refund',
  ],
  'maling send': [
    'gcash',
    'wrong send',
    'wrong number',
    'send money',
    'refund',
  ],
  'wrong number': [
    'gcash',
    'wrong send',
    'maling send',
    'refund',
  ],
  'unauthorized transaction': [
    'gcash',
    'account takeover',
    'report scam',
    'otp',
    'mpin',
  ],
  'account secure': [
    'gcash',
    'device registration',
    'otp',
    'mpin',
    'account takeover',
  ],
  'device registration': [
    'gcash',
    'account secure',
    'otp',
    'account takeover',
  ],
  sim: [
    'otp',
    'stolen phone',
    'lost phone',
    'nanakaw phone',
    'nawala phone',
    'nawala cellphone',
    'phone stolen',
    'lost sim',
    'sim replacement',
    'account access',
  ],
  phone: [
    'stolen phone',
    'lost phone',
    'nanakaw phone',
    'nawala phone',
    'nawala cellphone',
    'sim',
    'otp',
    'gcash',
    'maya',
  ],
  nanakaw: [
    'stolen',
    'stolen phone',
    'nanakaw phone',
    'lost phone',
    'phone stolen',
    'wallet',
  ],
  'stolen phone': [
    'lost phone',
    'nanakaw phone',
    'nawala phone',
    'nawala cellphone',
    'lost sim',
    'sim replacement',
    'imei',
    'ntc',
    'gcash',
    'otp',
  ],
  'lost phone': [
    'stolen phone',
    'nanakaw phone',
    'nawala phone',
    'nawala cellphone',
    'lost sim',
    'sim replacement',
    'imei',
    'ntc',
    'gcash',
    'otp',
  ],
  'nanakaw phone': [
    'stolen phone',
    'lost phone',
    'nawala cellphone',
    'lost sim',
    'sim replacement',
    'imei',
    'gcash',
    'otp',
  ],
  'nawala phone': [
    'lost phone',
    'stolen phone',
    'nawala cellphone',
    'lost sim',
    'sim replacement',
    'gcash',
    'otp',
  ],
  'nawala cellphone': [
    'lost phone',
    'stolen phone',
    'nanakaw phone',
    'lost sim',
    'sim replacement',
    'gcash',
    'otp',
  ],
  'lost sim': [
    'stolen phone',
    'lost phone',
    'sim replacement',
    'otp',
    'gcash',
    'telco',
  ],
  'sim replacement': [
    'lost sim',
    'stolen phone',
    'lost phone',
    'otp',
    'telco',
  ],
  imei: [
    'stolen phone',
    'lost phone',
    'ntc',
    'device blocking',
  ],
  'lost wallet': [
    'nawala wallet',
    'nanakaw wallet',
    'stolen wallet',
    'freeze card',
    'block card',
    'affidavit of loss',
    'lost id',
    'nawala id',
  ],
  'nawala wallet': [
    'lost wallet',
    'nanakaw wallet',
    'stolen wallet',
    'freeze card',
    'block card',
    'affidavit of loss',
    'lost id',
  ],
  'nanakaw wallet': [
    'lost wallet',
    'nawala wallet',
    'stolen wallet',
    'freeze card',
    'block card',
    'affidavit of loss',
    'lost id',
  ],
  'stolen wallet': [
    'lost wallet',
    'nawala wallet',
    'freeze card',
    'block card',
    'affidavit of loss',
  ],
  'freeze card': [
    'lost wallet',
    'block card',
    'atm card',
    'credit card',
    'debit card',
    'bank',
  ],
  'block card': [
    'lost wallet',
    'freeze card',
    'atm card',
    'credit card',
    'debit card',
    'bank',
  ],
  'affidavit of loss': [
    'lost wallet',
    'lost id',
    'nawala wallet',
    'driver license',
    'valid id',
  ],
  'lost id': [
    'lost wallet',
    'affidavit of loss',
    'valid id',
    'driver license',
    'national id',
  ],
  'nawala id': [
    'lost id',
    'lost wallet',
    'affidavit of loss',
    'valid id',
  ],
  trabaho: [
    'work',
    'job',
    'first job',
    'unang trabaho',
    'requirements',
    'pre employment requirements',
    'hr requirements',
    'resume',
    'interview',
    'sss',
    'philhealth',
    'pagibig',
    'tin',
    'nbi',
    'payroll',
  ],
  work: [
    'trabaho',
    'job',
    'first job',
    'unang trabaho',
    'requirements',
    'pre employment requirements',
    'hr requirements',
    'resume',
    'interview',
    'payroll',
  ],
  job: [
    'trabaho',
    'work',
    'first job',
    'unang trabaho',
    'requirements',
    'pre employment requirements',
    'hr requirements',
    'resume',
    'interview',
    'payroll',
  ],
  'first job': [
    'unang trabaho',
    'first job requirements',
    'pre employment requirements',
    'hr requirements',
    'first time jobseeker',
    'nbi first job',
    'sss philhealth pagibig tin',
  ],
  'unang trabaho': [
    'first job',
    'first job requirements',
    'pre employment requirements',
    'requirements',
    'hr requirements',
    'first time jobseeker',
    'nbi',
    'sss',
    'philhealth',
    'pagibig',
    'tin',
  ],
  'first job requirements': [
    'unang trabaho',
    'pre employment requirements',
    'hr requirements',
    'first time jobseeker',
    'nbi',
    'sss',
    'philhealth',
    'pagibig',
    'tin',
    'payroll',
  ],
  'pre employment requirements': [
    'first job requirements',
    'hr requirements',
    'nbi',
    'sss',
    'philhealth',
    'pagibig',
    'tin',
    'medical certificate',
    'payroll',
  ],
  'hr requirements': [
    'first job requirements',
    'pre employment requirements',
    'onboarding',
    'payroll',
    'sss',
    'philhealth',
    'pagibig',
    'tin',
  ],
  'first time jobseeker': [
    'first job',
    'first job requirements',
    'unang trabaho',
    'ra 11261',
    'barangay certificate',
    'free nbi',
    'nbi first job',
  ],
  'free nbi': [
    'first time jobseeker',
    'ra 11261',
    'barangay certificate',
    'nbi first job',
  ],
  'nbi first job': [
    'first time jobseeker',
    'first job requirements',
    'free nbi',
    'ra 11261',
    'barangay certificate',
  ],
  'sss philhealth pagibig tin': [
    'first job requirements',
    'government numbers',
    'hr requirements',
    'payroll',
    'bir form 1902',
  ],
  'barangay certificate': [
    'first time jobseeker',
    'ra 11261',
    'free nbi',
    'nbi first job',
  ],
  resume: [
    'cv',
    'biodata',
    'no experience',
    'walang experience',
    'first resume',
    'resume fresh graduate',
    'resume student',
    'fresh graduate',
    'first job',
    'job application',
  ],
  cv: [
    'resume',
    'biodata',
    'job application',
    'first job',
    'no experience',
  ],
  biodata: [
    'resume',
    'cv',
    'job application',
    'first job',
    'no experience',
  ],
  'no experience': [
    'resume',
    'walang experience',
    'first resume',
    'fresh graduate',
    'student',
    'first job',
    'job application',
  ],
  'walang experience': [
    'resume',
    'no experience',
    'first resume',
    'fresh graduate',
    'student',
    'unang trabaho',
  ],
  'first resume': [
    'resume',
    'no experience',
    'walang experience',
    'first job',
    'job application',
  ],
  'resume fresh graduate': [
    'resume',
    'fresh graduate',
    'no experience',
    'job application',
  ],
  'resume student': [
    'resume',
    'student',
    'no experience',
    'fresh graduate',
    'job application',
  ],
  interview: [
    'job interview',
    'first job',
    'first job interview',
    'interview answers',
    'interview walang experience',
    'answers',
    'hr',
    'expected salary',
    'tell me about yourself',
    'why should we hire you',
    'weakness interview',
    'strengths interview',
    'availability',
  ],
  'job interview': [
    'interview',
    'first job interview',
    'interview answers',
    'expected salary',
    'tell me about yourself',
  ],
  'first job interview': [
    'interview',
    'job interview',
    'interview answers',
    'unang trabaho',
    'walang experience',
  ],
  'interview answers': [
    'interview',
    'job interview',
    'tell me about yourself',
    'why should we hire you',
    'expected salary',
  ],
  'interview walang experience': [
    'interview',
    'first job interview',
    'walang experience',
    'fresh graduate',
  ],
  'expected salary': [
    'interview',
    'salary expectation',
    'job offer',
    'hr',
  ],
  'salary expectation': [
    'expected salary',
    'interview',
    'job offer',
    'hr',
  ],
  'tell me about yourself': [
    'interview',
    'interview answers',
    'first job interview',
  ],
  'why should we hire you': [
    'interview',
    'interview answers',
    'strengths interview',
  ],
  'weakness interview': [
    'interview',
    'interview answers',
    'tell me about yourself',
  ],
  'strengths interview': [
    'interview',
    'interview answers',
    'why should we hire you',
  ],
  sweldo: [
    'salary',
    'payday',
    'budget',
    'payroll',
    'kulang sweldo',
    'petsa de peligro',
    'bank account',
  ],
  sahod: [
    'salary',
    'payday',
    'budget',
    'payroll',
    'kulang sweldo',
    'petsa de peligro',
    'bank account',
  ],
  salary: [
    'sweldo',
    'sahod',
    'payday',
    'budget',
    'payroll',
    'salary short',
    'before payday',
  ],
  'kulang sweldo': [
    'salary short',
    'before payday',
    'petsa de peligro',
    'budget',
    'utang',
    'loan',
  ],
  'kulang sahod': [
    'salary short',
    'before payday',
    'petsa de peligro',
    'budget',
    'utang',
    'loan',
  ],
  'petsa de peligro': [
    'salary short',
    'before payday',
    'payday budget',
    'utang',
    'loan',
    'bills',
  ],
  'salary short': [
    'before payday',
    'payday budget',
    'cash shortfall',
    'debt',
    'loan',
  ],
  'before payday': [
    'salary short',
    'payday budget',
    'cash shortfall',
    'bills',
    'debt',
  ],
  payroll: [
    'salary',
    'sweldo',
    'bank account',
    'payroll account',
    'first job',
    'requirements',
  ],
  'payroll account': [
    'bank account',
    'payroll',
    'first job',
    'salary',
    'sweldo',
  ],
  'bank account': [
    'first bank account',
    'unang bank account',
    'savings account',
    'payroll account',
    'basic deposit account',
    'maintaining balance',
  ],
  bank: [
    'bank account',
    'savings account',
    'payroll account',
    'basic deposit account',
    'atm',
  ],
  'first bank account': [
    'bank account',
    'unang bank account',
    'savings account',
    'payroll account',
    'basic deposit account',
  ],
  'unang bank account': [
    'first bank account',
    'bank account',
    'savings account',
    'payroll account',
    'basic deposit account',
  ],
  'savings account': [
    'bank account',
    'first bank account',
    'maintaining balance',
    'deposit insurance',
    'pdic',
  ],
  'basic deposit account': [
    'bda',
    'bank account',
    'no maintaining balance',
    'starter account',
    'bsp',
  ],
  bda: [
    'basic deposit account',
    'bank account',
    'no maintaining balance',
    'bsp',
  ],
  'maintaining balance': [
    'bank account',
    'savings account',
    'fees',
    'dormancy fee',
  ],
  'no maintaining balance': [
    'basic deposit account',
    'bda',
    'bank account',
  ],
  'dormancy fee': [
    'bank account',
    'savings account',
    'maintaining balance',
    'fees',
  ],
  'deposit insurance': [
    'pdic',
    'bank account',
    'savings account',
  ],
  pdic: [
    'deposit insurance',
    'bank account',
    'savings account',
  ],
  rent: [
    'renting',
    'apartment',
    'bedspace',
    'deposit',
    'moving out',
    'landlord',
  ],
  apartment: [
    'rent',
    'renting',
    'bedspace',
    'deposit',
    'utilities',
  ],
  bedspace: [
    'rent',
    'renting',
    'apartment',
    'utilities',
    'moving out',
  ],
  upa: [
    'rent',
    'renting',
    'apartment',
    'deposit',
  ],
  bumukod: [
    'moving out',
    'rent',
    'budget',
    'utilities',
    'adulting',
  ],
  utilities: [
    'utility bills',
    'electricity',
    'water',
    'internet',
    'kuryente',
    'tubig',
  ],
  kuryente: [
    'electricity',
    'utility bills',
    'meralco',
    'disconnection',
  ],
  tubig: [
    'water',
    'utility bills',
    'maynilad',
    'disconnection',
  ],
  meralco: [
    'electricity',
    'kuryente',
    'utility bills',
  ],
  maynilad: [
    'water',
    'tubig',
    'utility bills',
  ],
  loan: [
    'online lending',
    'loan app',
    'ola',
    'utang',
    'pautang',
    'debt',
    'harassment',
    'collection',
  ],
  utang: [
    'loan',
    'online lending',
    'loan app',
    'ola',
    'pautang',
    'debt',
  ],
  pautang: [
    'loan',
    'online lending',
    'loan app',
    'utang',
    'ola',
  ],
  ola: [
    'online lending',
    'loan app',
    'loan',
    'utang',
    'harassment',
  ],
  harassment: [
    'online lending',
    'loan app',
    'collection',
    'data privacy',
  ],
  recruiter: [
    'fake job',
    'job scam',
    'illegal recruitment',
    'placement fee',
    'processing fee',
    'training fee',
    'work abroad',
    'tourist visa',
    'ofw',
    'dmw',
  ],
  recruitment: [
    'fake job',
    'job scam',
    'illegal recruitment',
    'placement fee',
    'processing fee',
    'training fee',
    'work abroad',
    'ofw',
    'dmw',
  ],
  ofw: [
    'fake job',
    'job scam',
    'illegal recruitment',
    'placement fee',
    'processing fee',
    'training fee',
    'work abroad',
    'tourist visa',
    'dmw',
    'poea',
  ],
  'illegal recruitment': [
    'fake job',
    'job scam',
    'recruiter',
    'placement fee',
    'processing fee',
    'training fee',
    'ofw',
    'dmw',
    'poea',
  ],
  'job scam': [
    'fake job',
    'recruiter',
    'illegal recruitment',
    'placement fee',
    'processing fee',
    'training fee',
    'work abroad',
  ],
  'fake job': [
    'job scam',
    'recruiter',
    'illegal recruitment',
    'placement fee',
    'processing fee',
    'training fee',
    'work abroad',
    'tourist visa',
  ],
  'placement fee': [
    'fake job',
    'job scam',
    'illegal recruitment',
    'recruiter',
    'processing fee',
    'training fee',
    'work abroad',
    'ofw',
  ],
  'processing fee': [
    'fake job',
    'job scam',
    'illegal recruitment',
    'recruiter',
    'placement fee',
    'training fee',
    'ofw',
  ],
  'training fee': [
    'fake job',
    'job scam',
    'illegal recruitment',
    'recruiter',
    'placement fee',
    'processing fee',
    'tesda',
  ],
  'work abroad': [
    'ofw',
    'fake job',
    'job scam',
    'illegal recruitment',
    'dmw',
    'poea',
    'tourist visa',
  ],
  'tourist visa': [
    'work abroad',
    'ofw',
    'fake job',
    'job scam',
    'illegal recruitment',
  ],
}
